export const SET_UPLOAD_STATUS = "SET_UPLOAD_STATUS";
export const SET_IMAGE = "SET_IMAGE";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";
export const START_NEW_POLYGON = "START_NEW_POLYGON";
export const ADD_POINT_TO_CURRENT = "ADD_POINT_TO_CURRENT";
export const UNDO_CURRENT_POINT = "UNDO_CURRENT_POINT";
export const CANCEL_CURRENT_POLYGON = "CANCEL_CURRENT_POLYGON";
export const FINISH_CURRENT_POLYGON = "FINISH_CURRENT_POLYGON";

export const DELETE_POLYGON = "DELETE_POLYGON";
export const UPDATE_POLYGON_CLASS = "UPDATE_POLYGON_CLASS";
export const RESET_ANNOTATIONS = "RESET_ANNOTATIONS";

export const SET_HOVERED_POLYGON = "SET_HOVERED_POLYGON";
export const SET_SELECTED_POLYGON = "SET_SELECTED_POLYGON";
export const CLEAR_POLYGONS = "CLEAR_POLYGONS";




